# Generated by Django 4.2.13 on 2024-05-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisky', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whisky',
            old_name='region',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='whisky',
            old_name='abv',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='whisky',
            name='age',
        ),
        migrations.RemoveField(
            model_name='whisky',
            name='image_url',
        ),
        migrations.AddField(
            model_name='whisky',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='whisky',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
