# Generated by Django 4.2.13 on 2024-05-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisky', '0002_rename_region_whisky_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisky',
            name='abv',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
