name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # 1. 소스 코드 체크아웃
    - name: Checkout source code
      uses: actions/checkout@v3
    
    # 2. AWS 인증 설정
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    
    # 3. ECR 로그인
    - name: Log in to Amazon ECR
      id: login-ecr
      run: |
        aws ecr get-login-password --region ap-northeast-1 | \
        docker login --username AWS --password-stdin 505502261492.dkr.ecr.ap-northeast-1.amazonaws.com

    # 4. 이미지 빌드 후 ECR 푸시
    - name: Build, tag, and push image to ECR
      env:
        ECR_REGISTRY: 505502261492.dkr.ecr.ap-northeast-1.amazonaws.com
        ECR_REPOSITORY: scotchbase
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # 5. scotchbase-manifest 레포지토리 체크아웃
    - name: Checkout manifest repository
      uses: actions/checkout@v3
      with:
        repository: uyh1556/scotchbase-manifest
        token: ${{ secrets.SCOTCHBASE_MANIFEST_TOKEN }}
        path: manifests

    # 6. kustomization.yaml 업데이트
    - name: Update Kustomize image tag
      run: |
        cd manifests/base
        kustomize edit set image 505502261492.dkr.ecr.ap-northeast-1.amazonaws.com/scotchbase:${{ github.sha }}
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.MANIFEST_REPO_TOKEN }}@github.com/uyh1556/scotchbase-manifest.git
        git commit -am "Update image tag to ${{ github.sha }}"
        git push